# ===================================================
# = Articoli Web Service - Versione Base
# ===================================================

server:
  port: 5051

spring:
  application: 
    name: Application
# ===================================================
# = DBMS PostgreSQL Parameters
# ===================================================
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5433/alphashop
    username: postgres
    password: pass123
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.schema-generation.scripts.action: none
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true  
