# ===================================================
# = Articoli Web Service - Versione Base
# ===================================================

server:
  port: 5051

spring:
  application: 
    name: Application
# ===================================================
# = DBMS PostgreSQL Parameters
# ===================================================
  datasource:
    url: jdbc:postgresql://localhost:5433/alphashop
    username: postgres
    password: pass123
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      javax.persistence.schema-generation.scripts.action: none
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true  
  sql:
    init:
      mode: always
      platform: postgres
