#==========================================================
#= User Management Service
#==========================================================
server:
  port: 8019
spring:
#==========================================================
#= DBMS MongoDB Parameters
#==========================================================
  data:
    mongodb:
      authentication-database: admin
      database: ms-users-test
      host: localhost
      password: pass123
      port: 27017
      username: mario
      auto-index-creation: true