#==========================================================
#= User Management Service
#==========================================================
spring:
  data:
    mongodb:
      database: ms-users-test