#==========================================================
#= User Management Service
#==========================================================
server:
  port: 8019
spring:
  application:
    name: UserManagementService
#==========================================================
#= DBMS MongoDB Parameters
#==========================================================
  data:
    mongodb:
      authentication-database: admin
      database: ms-users
      host: localhost
      password: pass123
      port: 27017
      username: mario
      auto-index-creation: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true