# ==============================================================
# = JWT AUTHENTICATION SERVICE
# ==============================================================
server:
    port: 5051

# ==============================================================
# = USER MANAGEMENT SERVICE
# ==============================================================
user-service:
  serverUrl: http://user-management:5051/api/users/