# ===================================================
# = Articoli Web Service - Versione Base
# ===================================================
server:
  port: 5051

spring:
  application: 
    name: Application
# ===================================================
# = DBMS PostgreSQL Parameters
# ===================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5433/alphashop
    username: postgres
    password: pass123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ===================================================
# = CONSTANTS
# ===================================================
codartArtNotDeletable: "abcTest"


