# ===================================================
# = Articles Web Service
# ===================================================
server:
  port: 5051

spring:
  application: 
    name: Articles Web Service
# ===================================================
# = DBMS PostgreSQL Parameters
# ===================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5433/alphashop
    username: postgres
    password: pass123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
# ===================================================
# = CONSTANTS
# ===================================================
codartNotDeletable: "abcTest"
# DEBUG
profile:
  property:
    value: "This the the application.yaml file"
# ==============================================================
# = Security JWT' 
# ==============================================================
security:
    header: Authorization
    secret: 2f70d44e3613b8a1370eafeb8912bc4e487eb077ee1bf777304c277639311429