# ===================================================
# = Articles Web Service
# ===================================================
spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/alphashop
